#!/usr/bin/env python3
"""Generates the per-build key material used to obfuscate the embedded
frontend assets (see tools/embed_resources.py --obfuscate and
src/kronos/AssetObfuscation.cpp).

Emits TWO files:

  <out_header>   a C++ header defining the key in a deliberately scattered,
                 individually-masked form -- four small arrays with
                 misleading names plus a uint32 mask seed, never a
                 contiguous 32-byte literal. src/kronos/AssetObfuscation.cpp
                 reassembles the real 32-byte key from these at runtime.
  <out_keybin>   the same 32 raw key bytes, for tools/embed_resources.py to
                 read when it applies the matching transform at build time.

IMPORTANT: this is OBFUSCATION, not encryption. The key is present in the
shipped binary (it has to be -- the app decodes its own assets with no user
input), so a determined reverse-engineer can always recover it. The point is
to defeat `strings`, a text editor, and casual inspection, and to make
pulling the frontend back out cost real effort rather than seconds.

The key is generated ONCE per build tree: the CMake custom command that runs
this has no DEPENDS, so it only re-runs when its outputs are missing (a fresh
checkout / clean build dir / CI). Reconfiguring an existing build tree keeps
the same key, so incremental builds don't churn every embedded asset.
"""

import os
import secrets
import sys


def mask_byte(seed: int, p: int) -> int:
    """Must stay byte-for-byte identical to reconstructKey() in
    src/kronos/AssetObfuscation.cpp."""
    return (((seed >> ((p & 3) * 8)) & 0xFF) ^ ((p * 0x2B) & 0xFF) ^ 0x5C) & 0xFF


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <out_header> <out_keybin>", file=sys.stderr)
        return 1

    out_header, out_keybin = sys.argv[1:3]

    key = secrets.token_bytes(32)
    seed = secrets.randbits(32)

    # Scatter: array a = p % 4, slot = p // 4, value = key[p] ^ mask(seed, p).
    scattered = [[0] * 8 for _ in range(4)]
    for p in range(32):
        scattered[p % 4][p // 4] = key[p] ^ mask_byte(seed, p)

    names = ["kLayoutTableA", "kLayoutTableB", "kPadRunLengths", "kGlyphAdvance"]

    os.makedirs(os.path.dirname(out_header), exist_ok=True)
    with open(out_header, "w") as h:
        h.write("#pragma once\n\n")
        h.write("// GENERATED by tools/gen_asset_key.py -- do not edit.\n")
        h.write("// Scattered/masked frontend-asset obfuscation key; reassembled\n")
        h.write("// at runtime by src/kronos/AssetObfuscation.cpp.\n\n")
        h.write("namespace kronos::asset_key_detail {\n\n")
        for name, arr in zip(names, scattered):
            body = ", ".join(f"0x{b:02x}" for b in arr)
            h.write(f"inline constexpr unsigned char {name}[8] = {{ {body} }};\n")
        h.write(f"\ninline constexpr unsigned int kAdvanceSeed = 0x{seed:08x}u;\n\n")
        h.write("}  // namespace kronos::asset_key_detail\n")

    os.makedirs(os.path.dirname(out_keybin) or ".", exist_ok=True)
    with open(out_keybin, "wb") as k:
        k.write(key)

    print(f"Generated fresh asset obfuscation key -> {out_header}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
